# jekyll config
safe:        true
lsi:         false
highlighter: pygments
permalink:   /news/:title/
exclude:     [vendor]
markdown:    redcarpet
redcarpet:
    extensions: [tables]

# custom config
cachebust: 1